// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name                  *string                `json:",omitempty"`
	Description           *string                `json:",omitempty"`
	SecureParameter       *SecureParameter       `json:",omitempty"`
	Parameter             *Parameter             `json:",omitempty"`
	ProviderConfiguration *ProviderConfiguration `json:",omitempty"`
	VpcConfig             *VpcConfig             `json:",omitempty"`
	Tags                  []Tag                  `json:",omitempty"`
	Id                    *string                `json:",omitempty"`
	ARN                   *string                `json:",omitempty"`
	Version               *string                `json:",omitempty"`
}

// SecureParameter is autogenerated from the json schema
type SecureParameter struct {
	KmsKeyId             *string               `json:",omitempty"`
	GenerateSecretString *GenerateSecretString `json:",omitempty"`
}

// GenerateSecretString is autogenerated from the json schema
type GenerateSecretString struct {
	ExcludeUppercase        *bool   `json:",omitempty"`
	RequireEachIncludedType *bool   `json:",omitempty"`
	IncludeSpace            *bool   `json:",omitempty"`
	ExcludeCharacters       *string `json:",omitempty"`
	GenerateStringKey       *string `json:",omitempty"`
	PasswordLength          *int    `json:",omitempty"`
	ExcludePunctuation      *bool   `json:",omitempty"`
	ExcludeLowercase        *bool   `json:",omitempty"`
	SecretStringTemplate    *string `json:",omitempty"`
	ExcludeNumbers          *bool   `json:",omitempty"`
}

// Parameter is autogenerated from the json schema
type Parameter struct {
	Policies *string `json:",omitempty"`
	Tier     *string `json:",omitempty"`
}

// ProviderConfiguration is autogenerated from the json schema
type ProviderConfiguration struct {
	Endpoint             *string `json:",omitempty"`
	Username             *string `json:",omitempty"`
	Password             *string `json:",omitempty"`
	Proxy                *string `json:",omitempty"`
	TLS                  *string `json:",omitempty"`
	MaxConnLifetimeSec   *int    `json:",omitempty"`
	MaxOpenConns         *int    `json:",omitempty"`
	AuthenticationPlugin *string `json:",omitempty"`
}

// VpcConfig is autogenerated from the json schema
type VpcConfig struct {
	SecurityGroupIds []string `json:",omitempty"`
	SubnetIds        []string `json:",omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
